colors {
background #0f111a
statusline #f8f8f2
separator #0f111a
focused_workspace #89b4fa #89b4fa #0f111a
active_workspace #313244 #313244 #f8f8f2
inactive_workspace #0f111a #0f111a #a6adc8
urgent_workspace #f38ba8 #f38ba8 #0f111a
}
